import streamlit as st
import pandas as pd


st.set_page_config(layout="wide")
st.title("📊 Raid Performance Dashboard")

report_data = {
  "players": [
    {
      "rank": 1,
      "name": "Total",
      "total_damage": 102943680,
      "dps": 12049.8,
      "useful_damage": 12049.8,
      "total_heal": 22005624,
      "hps": 2575.8,
      "damage_taken": 0,
      "dtps": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 0
    },
    {
      "rank": 2,
      "name": "Xiphoswl",
      "total_damage": 7472095,
      "dps": 874.6,
      "useful_damage": 874.6,
      "total_heal": 100123,
      "hps": 11.7,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 19,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 7,
      "spell_curse_of_agony": 64,
      "spell_curse_of_doom": 20,
      "spell_shadow_vulnerability": 417,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 0
    },
    {
      "rank": 3,
      "name": "Nerfmydots",
      "total_damage": 7278398,
      "dps": 851.9,
      "useful_damage": 851.9,
      "total_heal": 97120,
      "hps": 11.3,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 16,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 16,
      "spell_curse_of_doom": 18,
      "spell_shadow_vulnerability": 400,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 1,
      "spell_eye_of_the_night": 0,
      "mana_potion": 0
    },
    {
      "rank": 4,
      "name": "Skandal",
      "total_damage": 7215116,
      "dps": 844.5,
      "useful_damage": 844.5,
      "total_heal": 409503,
      "hps": 47.9,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 12,
      "destruction_potion": 0,
      "goblin_sapper_charge": 2,
      "super_sapper_charge": 3,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 4,
      "spell_scroll_of_agility": 6,
      "spell_elixir_of_demonslaying": 7,
      "spell_drums_of_battle": 11,
      "spell_braided_eternium_chain": 2,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 5
    },
    {
      "rank": 5,
      "name": "Rime",
      "total_damage": 6913913,
      "dps": 809.2,
      "useful_damage": 809.2,
      "total_heal": 425,
      "hps": 0,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 0,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 3,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 10,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 19
    },
    {
      "rank": 6,
      "name": "Zagorhunt",
      "total_damage": 6854546,
      "dps": 802.3,
      "useful_damage": 802.3,
      "total_heal": 267920,
      "hps": 31.3,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 18,
      "destruction_potion": 0,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 1,
      "spell_drums_of_battle": 22,
      "spell_braided_eternium_chain": 2,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 2
    },
    {
      "rank": 7,
      "name": "Laqueesha",
      "total_damage": 6055083,
      "dps": 708.7,
      "useful_damage": 708.7,
      "total_heal": 89029,
      "hps": 10.4,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 12,
      "destruction_potion": 0,
      "goblin_sapper_charge": 4,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 58,
      "spell_demoralizing_shout": 32,
      "spell_pummel": 16,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 4,
      "spell_scroll_of_agility": 4,
      "spell_elixir_of_demonslaying": 3,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 2,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 0
    },
    {
      "rank": 8,
      "name": "Yeslife",
      "total_damage": 5948663,
      "dps": 696.3,
      "useful_damage": 696.3,
      "total_heal": 1700,
      "hps": 0.1,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 0,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 23
    },
    {
      "rank": 9,
      "name": "Pyrones",
      "total_damage": 5824008,
      "dps": 681.7,
      "useful_damage": 681.7,
      "total_heal": 136614,
      "hps": 15.9,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 20,
      "destruction_potion": 0,
      "goblin_sapper_charge": 3,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 37,
      "spell_sunder_armor": 200,
      "spell_demoralizing_shout": 21,
      "spell_pummel": 13,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 6,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 4,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 2,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 0
    },
    {
      "rank": 10,
      "name": "Jezzpubby",
      "total_damage": 5716524,
      "dps": 669.1,
      "useful_damage": 669.1,
      "total_heal": 73423,
      "hps": 8.5,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 18,
      "goblin_sapper_charge": 2,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 64,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 2,
      "spell_shadow_vulnerability": 371,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 1,
      "mana_potion": 0
    },
    {
      "rank": 11,
      "name": "Sibylle",
      "total_damage": 5461751,
      "dps": 639.3,
      "useful_damage": 639.3,
      "total_heal": 77102,
      "hps": 9.0,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 15,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 107,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 17,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 239,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 21,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 2,
      "spell_eye_of_the_night": 2,
      "mana_potion": 1
    },
    {
      "rank": 12,
      "name": "Zappiboy",
      "total_damage": 5157360,
      "dps": 603.6,
      "useful_damage": 603.6,
      "total_heal": 76599,
      "hps": 8.9,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 7,
      "destruction_potion": 0,
      "goblin_sapper_charge": 1,
      "super_sapper_charge": 0,
      "spell_resurrects": 2,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 2,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 10,
      "spell_purge": 2,
      "spell_scroll_of_strength": 5,
      "spell_scroll_of_agility": 5,
      "spell_elixir_of_demonslaying": 3,
      "spell_drums_of_battle": 23,
      "spell_braided_eternium_chain": 1,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 0
    },
    {
      "rank": 13,
      "name": "Shurielle",
      "total_damage": 5143972,
      "dps": 602.1,
      "useful_damage": 602.1,
      "total_heal": 67856,
      "hps": 7.9,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 15,
      "destruction_potion": 0,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 7,
      "spell_scroll_of_agility": 7,
      "spell_elixir_of_demonslaying": 6,
      "spell_drums_of_battle": 19,
      "spell_braided_eternium_chain": 2,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 10
    },
    {
      "rank": 14,
      "name": "Mikeoheal",
      "total_damage": 4877006,
      "dps": 570.8,
      "useful_damage": 570.8,
      "total_heal": 4992,
      "hps": 0.5,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 15,
      "goblin_sapper_charge": 1,
      "super_sapper_charge": 0,
      "spell_resurrects": 1,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 1,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 10,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 24,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 2,
      "spell_eye_of_the_night": 2,
      "mana_potion": 1
    },
    {
      "rank": 15,
      "name": "Goatjo",
      "total_damage": 4338715,
      "dps": 507.8,
      "useful_damage": 507.8,
      "total_heal": 205146,
      "hps": 24.0,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 14,
      "destruction_potion": 0,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 10,
      "spell_purge": 8,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 3,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 1,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 0
    },
    {
      "rank": 16,
      "name": "Keljin",
      "total_damage": 3605001,
      "dps": 421.9,
      "useful_damage": 421.9,
      "total_heal": 59792,
      "hps": 6.9,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 1,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 178,
      "spell_insect_swarm": 119,
      "spell_innervate": 9,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 1,
      "spell_eye_of_the_night": 1,
      "mana_potion": 15
    },
    {
      "rank": 17,
      "name": "Xyeth",
      "total_damage": 3363838,
      "dps": 393.7,
      "useful_damage": 393.7,
      "total_heal": 567196,
      "hps": 66.3,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 17,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 2,
      "spell_eye_of_the_night": 2,
      "mana_potion": 5
    },
    {
      "rank": 18,
      "name": "Sviznakrava",
      "total_damage": 3359047,
      "dps": 393.1,
      "useful_damage": 393.1,
      "total_heal": 462402,
      "hps": 54.1,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 8,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 24,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 2,
      "spell_natures_swiftness": 3,
      "spell_ancestral_spirit": 24,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 10,
      "spell_purge": 2,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 19,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 2
    },
    {
      "rank": 19,
      "name": "Lispe",
      "total_damage": 2849514,
      "dps": 333.5,
      "useful_damage": 333.5,
      "total_heal": 141907,
      "hps": 16.6,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 0,
      "goblin_sapper_charge": 1,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 3,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 2,
      "spell_scroll_of_agility": 2,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 8,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 0
    },
    {
      "rank": 20,
      "name": "Kittym",
      "total_damage": 2771013,
      "dps": 324.3,
      "useful_damage": 324.3,
      "total_heal": 149599,
      "hps": 17.5,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 0,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 8,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 4,
      "spell_scroll_of_agility": 4,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 15,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 0
    },
    {
      "rank": 21,
      "name": "Paws",
      "total_damage": 1995338,
      "dps": 233.5,
      "useful_damage": 233.5,
      "total_heal": 351892,
      "hps": 41.1,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 0,
      "goblin_sapper_charge": 8,
      "super_sapper_charge": 3,
      "spell_resurrects": 2,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 2,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 2
    },
    {
      "rank": 22,
      "name": "Flurryx",
      "total_damage": 407793,
      "dps": 47.7,
      "useful_damage": 47.7,
      "total_heal": 4202029,
      "hps": 491.8,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 0,
      "goblin_sapper_charge": 1,
      "super_sapper_charge": 0,
      "spell_resurrects": 4,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 9,
      "spell_natures_swiftness": 25,
      "spell_ancestral_spirit": 4,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 10,
      "spell_purge": 11,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 13,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 23
    },
    {
      "rank": 23,
      "name": "Hellhealer",
      "total_damage": 116606,
      "dps": 13.6,
      "useful_damage": 13.6,
      "total_heal": 3174037,
      "hps": 371.5,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 0,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 8,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 10,
      "spell_natures_swiftness": 14,
      "spell_ancestral_spirit": 8,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 10,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 16
    },
    {
      "rank": 24,
      "name": "Frizzo",
      "total_damage": 91574,
      "dps": 10.7,
      "useful_damage": 10.7,
      "total_heal": 3811375,
      "hps": 446.1,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 0,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 0,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 7,
      "spell_natures_swiftness": 11,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 9,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 7,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 15
    },
    {
      "rank": 25,
      "name": "Lillakatten",
      "total_damage": 84817,
      "dps": 9.9,
      "useful_damage": 9.9,
      "total_heal": 4058829,
      "hps": 475.0,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 2,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 6,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 0,
      "spell_natures_swiftness": 0,
      "spell_ancestral_spirit": 0,
      "spell_resurrection": 6,
      "spell_redemption": 0,
      "spell_bloodlust": 0,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 16
    },
    {
      "rank": 26,
      "name": "Etherial",
      "total_damage": 41989,
      "dps": 4.9,
      "useful_damage": 4.9,
      "total_heal": 3419014,
      "hps": 400.2,
      "damage_taken": 0,
      "dtps": 0,
      "haste_potion": 0,
      "destruction_potion": 0,
      "goblin_sapper_charge": 0,
      "super_sapper_charge": 0,
      "spell_resurrects": 8,
      "spell_thunder_clap": 0,
      "spell_sunder_armor": 0,
      "spell_demoralizing_shout": 0,
      "spell_pummel": 0,
      "spell_faerie_fire": 0,
      "spell_insect_swarm": 0,
      "spell_innervate": 0,
      "spell_curse_of_the_elements": 0,
      "spell_curse_of_recklessness": 0,
      "spell_curse_of_tongues": 0,
      "spell_curse_of_agony": 0,
      "spell_curse_of_doom": 0,
      "spell_shadow_vulnerability": 0,
      "spell_mana_tide_totem": 10,
      "spell_natures_swiftness": 16,
      "spell_ancestral_spirit": 8,
      "spell_resurrection": 0,
      "spell_redemption": 0,
      "spell_bloodlust": 10,
      "spell_purge": 0,
      "spell_scroll_of_strength": 0,
      "spell_scroll_of_agility": 0,
      "spell_elixir_of_demonslaying": 0,
      "spell_drums_of_battle": 0,
      "spell_braided_eternium_chain": 0,
      "spell_chain_of_the_twilight_owl": 0,
      "spell_eye_of_the_night": 0,
      "mana_potion": 8
    }
  ]
}

df = pd.DataFrame(report_data["players"])
df = df[df["name"] != "Total"]


def top_table(title, column, n=20, column_display_name="used"):
    st.markdown(f"**{title}**")
    sorted_df = (
        df[["name", column]]
        .query(f"{column} > 0")  # Filter out zero values
        .sort_values(by=column, ascending=False)
        .head(n)
    )

    if column_display_name:
        sorted_df = sorted_df.rename(columns={column: column_display_name})
    
    st.dataframe(sorted_df, use_container_width=True, hide_index=True)

def bar_chart(title, column, n=10):
    st.subheader(title)
    chart_data = (
        df[["name", column]]
        .query(f"{column} > 0")  # Filter out zero values
        .sort_values(by=column, ascending=False)
        .head(n)
    )
    
    chart_data['ranked_name'] = [f"{' ' * (n-i)}{name}" for i, name in enumerate(chart_data['name'])]
    chart_data = chart_data.set_index('ranked_name')[column]
    
    st.bar_chart(chart_data)

# === DPS / HPS Bar Charts ===
col1, col2 = st.columns(2)
with col1:
    bar_chart("Top 10 Damage Dealers (DPS)", "dps", n=10)
with col2:
    bar_chart("Top 5 Healers (HPS)", "hps", n=5)


# === Potion Usage ===
st.subheader("🧪 Potions")
col1, col2, col3, col4 = st.columns(4)
with col1:
    top_table("HASTE POTION", "haste_potion")
with col2:
    top_table("DESTRUCTION POTION", "destruction_potion")
with col3:
    top_table("ELIXIR OF DEMONSLAYING", "spell_elixir_of_demonslaying")
with col4:
    top_table("MANA POTION", "mana_potion")


# === Sappers ===
st.subheader("💥 Sappers")
col1, col2 = st.columns(2)
with col1:
    top_table("SUPER SAPPER CHARGE", "super_sapper_charge")
with col2:
    top_table("GOBLIN SAPPER CHARGE", "goblin_sapper_charge")


# === Warriors ===
st.subheader("⚔️ Warriors")
col1, col2, col3, col4 = st.columns(4)
with col1:
    top_table("SUNDER ARMOR", "spell_sunder_armor")
with col2:
    top_table("DEMORALIZING SHOUT", "spell_demoralizing_shout")
with col3:
    top_table("THUNDER CLAP", "spell_thunder_clap")
with col4:
    top_table("PUMMEL", "spell_pummel")


# === Druids ===
st.subheader("🐻 Druids")
col1, col2, col3 = st.columns(3)
with col1:
    top_table("FAERIE FIRE", "spell_faerie_fire")
with col2:
    top_table("INSECT SWARM", "spell_insect_swarm")
with col3:
    top_table("INNERVATE", "spell_innervate")


# === Warlocks ===
st.subheader("💀 Warlocks")
col1, col2, col3, col4, col5, col6 = st.columns(6)
with col1:
    top_table("CURSE OF THE ELEMENTS", "spell_curse_of_the_elements")
with col2:
    top_table("CURSE OF RECKLESSNESS", "spell_curse_of_recklessness")
with col3:
    top_table("CURSE OF TONGUES", "spell_curse_of_tongues")
with col4:
    top_table("CURSE OF AGONY", "spell_curse_of_agony")
with col5:
    top_table("CURSE OF DOOM", "spell_curse_of_doom")
with col6:
    top_table("SHADOW VULNERABILITY", "spell_shadow_vulnerability")


# === Shamans ===
st.subheader("🌀 Shamans")
col1, col2, col3, col4 = st.columns(4)
with col1:
    top_table("BLOODLUST", "spell_bloodlust")
with col2:
    top_table("MANA TIDE TOTEM", "spell_mana_tide_totem")
with col3:
    top_table("NATURE'S SWIFTNESS", "spell_natures_swiftness")
with col4:
    top_table("PURGE", "spell_purge")


# === Necks ===
st.subheader("💎 Necks")
col1, col2, col3 = st.columns(3)
with col1:
    top_table("BRAIDED ETERNIUM CHAIN", "spell_braided_eternium_chain")
with col2:
    top_table("CHAIN OF THE TWILIGHT OWL", "spell_chain_of_the_twilight_owl")
with col3:
    top_table("EYE OF THE NIGHT", "spell_eye_of_the_night")


# === Other ===
st.subheader("🎭 Other")
col1, col2, col3 = st.columns(3)
with col1:
    top_table("SCROLL OF STRENGTH", "spell_scroll_of_strength")
with col2:
    top_table("SCROLL OF AGILITY", "spell_scroll_of_agility")
with col3:
    top_table("DRUMS OF BATTLE", "spell_drums_of_battle")

# === Resurrects ===
st.subheader("✝️ Resurrects")
top_table("Resurrects", "spell_resurrects")